const musicSceneElement = document.getElementById("music-scene");
const musicSongs = [
 {title:"Bad",artist:"wave to earth",file:"wave to earth - bad.mp3",label:"THE BEGINNING",reason:"Bagian “face to face, we just smile…” ini tuh relate bangett sama kita😭 awal ketemu cuma saling senyum, terus kenalan dan ngobrol2 ajaa. Siapa juga yang nyangka awalnya cuma gitu terus sekarang malah jadi jadian sama kamuu xixixi 🥹🤍"},
 {title:"The Joker & The Queen",artist:"Ed Sheeran ft. Taylor Swift",file:"Ed Sheeran - The Joker And The Queen (feat. Taylor Swift) [Official Video].mp3",label:"SOMEHOW, IT'S YOU",reason:"Gatau kenapaa lagu ini tuh berasa kita banget 🥹 kaya dari sekian banyak orang, kok bisa yaa akhirnya aku ketemu kamu dan kamu ketemu aku xixixi. Walaupun kita sama-sama nggak sempurna dan kadang suka bikin kesel satu sama lain😭 tapi tetep aja ujung-ujungnya aku seneng banget bisa punya kamu 🥺🤍 kaya somehow kamu tuh emang soulmate aku deh xixixi."},
 {title:"Queen of My Heart",artist:"Westlife",file:"Westlife_-_Queen_of_My_Heart_(mp3.pm).mp3",label:"EVEN FROM AFAR",reason:"Ini tuh cocok bangett buat kita yang LDR 😭 walaupun kita jauhh, kamu tetep punya tempat paling spesial di hati aku getooohhhh 🥺🤍 kamu nya dah pulangg eh taunya aku yg beda pulau skrg :(( Semoga nanti nggak lama2 lagi yaa dan kita bisa sering bareng2 tanpa harus sedih karena jarak 🥹🤍"},
 {title:"On Bended Knee",artist:"Boyz II Men",file:"Boys_To_Men_-_ON_BENDED_KNEE_(mp3.pm).mp3",label:"THE ONE I CAN'T FORGET",reason:"INI NIH 😭😭 lagu yang kamu play pas nembak aku di mobillll xixixixi 🥹🤍 Mana pas banget ada ambulance lewat lagiii 😭😭 wkwkwk random banget tapi justru itu yang bikin momennya nggak akan aku lupain. Jadi setiap denger lagu ini pasti langsung kebayang kamu, mobil itu, dan momen kamu nembak aku xixixi🥺🤍"},
 {title:"Lesung Pipi",artist:"Raim Laode",file:"Raim Laode - Lesung Pipi ( video lirik official ).mp3",label:"LITTLE THINGS",reason:"Aku pertama kali tau lagu ini dari kamuuu 🥺 dulu kamu suka banget play lagu ini pas kita motoran, terus lama lama kita jadi sering dengerin bareng setiap motoran xixixi. Jadi sekarang kalau denger lagu ini tuh rasanya langsung keinget kamu dan momen kita di motorrr 😭🤍 Padahal cuma lagu dan cuma motoran biasa, tapi entah kenapa jadi salah satu memory kecil yang aku suka bangettt 🥹"},
 {title:"Evergreen",artist:"Westlife",file:"Westlife_-_Evergreen_(mp3.pm).mp3",label:"ONE NEW YEAR",reason:"Karena ini lagu yang kita dengerin pas tahun baruuuu sama kamuuu 😭🤍 iyaattt petasann ituu xixixixixi 🎆😭 Jadi setiap denger lagu ini langsung kebayang lagi momen itu. Tahun baru, petasan, terus ada kamuuu 🥹🤍 sesimpel itu tapi aku sukaaa banget, kaya pengen ngulang lagi sayang bgt tempatnya dah longsor🥲"},
 {title:"Rahasia Hati",artist:"Nidji",file:"NIDJI - Rahasia Hati (Official Music Video).mp3",label:"AFTER YOU SAID YES",reason:"Kamu bilang ini lagu yang kamu dengerin setelah nembak aku yaaa kalau aku nggak salah 😭🥺 terus aku jadi ikutan dengerin jugaaa. Jadi sekarang lagu ini tuh kaya punya cerita kita sendiri apyu🤍"}
];
const musicAudio = new Audio(); let musicIndex=0;
const musicEl = (id) => document.getElementById(id);
const formatMusicTime = (value) => { const total=Math.floor(Number.isFinite(value)?value:0); return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`; };
function renderMusic() { const song=musicSongs[musicIndex]; if (!musicAudio.paused) window.audioManager.pauseForeground(musicAudio); musicAudio.src=`assets/music/${encodeURIComponent(song.file)}`; musicEl("music-count").textContent=`${String(musicIndex+1).padStart(2,"0")} / 07`; musicEl("music-song-title").textContent=song.title; musicEl("music-artist").textContent=song.artist; musicEl("music-label").textContent=song.label; musicEl("music-reason").textContent=song.reason; musicEl("music-ending").hidden=musicIndex!==6; updateMusicUi(); }
function updateMusicUi(){const toggle=musicEl("music-toggle"); if(toggle)toggle.textContent=musicAudio.paused?"▶":"❚❚"; const progress=musicEl("music-progress"); if(progress){progress.max=Number.isFinite(musicAudio.duration)?musicAudio.duration:0;progress.value=musicAudio.currentTime;} musicEl("music-current-time").textContent=formatMusicTime(musicAudio.currentTime);musicEl("music-duration").textContent=formatMusicTime(musicAudio.duration);musicEl("music-vinyl").classList.toggle("is-playing",!musicAudio.paused);}
function initializeMusicScene(){renderMusic();}
musicEl("music-toggle").addEventListener("click",()=>{if(musicAudio.paused)window.audioManager.playForeground(musicAudio,"music-scene").catch(()=>{});else window.audioManager.pauseForeground(musicAudio);updateMusicUi();});
musicEl("music-previous").addEventListener("click",()=>{if(musicIndex>0){musicIndex--;renderMusic();}}); musicEl("music-next-song").addEventListener("click",()=>{if(musicIndex<musicSongs.length-1){musicIndex++;renderMusic();}}); musicEl("music-progress").addEventListener("input",e=>{musicAudio.currentTime=Number(e.target.value);updateMusicUi();}); musicAudio.addEventListener("timeupdate",updateMusicUi);musicAudio.addEventListener("loadedmetadata",updateMusicUi);musicAudio.addEventListener("ended",()=>{window.audioManager.pauseForeground(musicAudio);updateMusicUi();});
musicEl("music-back").addEventListener("click",()=>{musicSceneElement.classList.remove("active");ourMemoriesScene.classList.add("active");initializeOurMemoriesScene();});
musicEl("music-next-scene").addEventListener("click",()=>{if(typeof showFinalMessageScene==="function")showFinalMessageScene();});
